# Site settings
title: OpenData.cz
email: klimek@opendata.cz
author: 
    name: "Jakub Klímek"
    twitter: jakub_klimek

description: > # this means to ignore newlines until "baseurl:"
  OpenData.cz is an initiative for transparend data infrastructure
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://opendata.cz" # the base hostname & protocol for your site

# Build settings
excerpt_separator: <!--more-->

gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
